library(DiagrammeR)
library(dplyr)


edges <- create_edge_df(
    from = c(1	,
             1	,
             2	,
             3	,
             3	,
             3	,
             4	,
             4	,
             5	,
             6	,
             6	,
             7	,
             7	,
             8	,
             8	,
             9	,
             9	,
             10	,
             11	,
             12	,
             12	,
             13	,
             13	,
             13	,
             14	,
             14	,
             14	,
             14	,
             15	,
             16	,
             16	,
             17	,
             17	,
             18	,
             19	,
             20	,
             22	,
             23	,
             23	,
             23	,
             24	,
             24	,
             25	,
             25	,
             25	,
             26	,
             27	,
             27	,
             28	,
             28	,
             30	,
             32	,
             35	,
             37),
    to = c(17	,
           18	,
           19	,
           20	,
           21	,
           30	,
           18	,
           22	,
           23	,
           23	,
           30	,
           18	,
           22	,
           18	,
           24	,
           18	,
           22	,
           25	,
           17	,
           21	,
           30	,
           26	,
           27	,
           28	,
           22	,
           26	,
           27	,
           28	,
           18	,
           18	,
           21	,
           29	,
           30	,
           31	,
           32	,
           38	,
           20	,
           30	,
           33	,
           34	,
           20	,
           35	,
           30	,
           34	,
           36	,
           22	,
           37	,
           39	,
           37	,
           39	,
           38	,
           38	,
           30	,
           30	)
)


nodes <- create_node_df(n = 39,
               label = c("Medical Assistance Program",
                         "Medicare Supplementary Medical Insurance",
                         "Highway Planning and Construction",
                         "National School Lunch Program",
                         "Title 1 Grants to Local Educational Agencies",
                         "Special Education Grants to States",
                         "Head Start",
                         "SNAP",
                         "WIC",
                         "Health Center Programs (Community, Migrant, Homeless, Public Housing)",
                         "Foster Care Title IV-E",
                         "Child Care Mandatory and Matching Funds of the Child Care and Development Fund",
                         "Section 8 Housing Choice Vouchers",
                         "Section 8 Housing Assistance Payments Program (Project-based)",
                         "State Childrens Health Insurance Program",
                         "Low-Income Home Energy Assistance",
                         "per capita income (BEA)",
                         "poverty guidelines",
                         "geographic practice cost indices (HHS)",
                         "urban/rural classification",
                         "state median income (ACS)",
                         "consumer price index for urban consumers (BLS)",
                         "Model-based Small Area Income and Poverty Estimates",
                         "local area unemployment statistics (BLS)",
                         "index of medical underservice (HHS)",
                         "renewal funding allocation factors (HUD)",
                         "median family income",
                         "fair market rent",
                         "personal income (census)",
                         "population estimates",
                         "poverty thresholds (census)",
                         "core-based statistical areas",
                         "median household income (ACS)",
                         "percentage of population in poverty (ACS)",
                         "new entrants and reentrants to labor force",
                         "percentage of population 65+ (ACS)",
                         "metro area definitions (CBSAs)",
                         "population count (census)	",
                         "nominal fair market rent (ACS)"),
               type = c("program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "program",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator",
                        "indicator"),
               shape = c("rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "rectangle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle"	,
                         "circle")
            )


graph <- create_graph(nodes_df = nodes,
               edges_df = edges) %>% 
  colorize_node_attrs(
                 node_attr_from = type,
                 node_attr_to = color)

render_graph(graph)